- hosts: all
  become: yes
  tasks:
  
   - name: Disabling Swap on all nodes
     shell: swapoff -a

   - name: Commenting Swap entries in /etc/fstab
     replace:
      path: /etc/fstab
      regexp: '(.*swap*)'
      replace: '#\1'
     
   - name: remove firewalld
     package:
       name: firewalld
       state: absent
     
   - name: install Docker
     yum:
       name: docker
       state: present
       update_cache: true

   - name: start Docker
     service:
       name: docker
       state: started

   - name: Ensure group "docker" exists
     group:
       name: docker
       state: present
       
   - name: Adding user centos to group docker
     user: 
        name: centos
        shell: /bin/bash
        groups: docker,wheel
        append: yes

   - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      state: present

   - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present

   - name: add Kubernetes' YUM repository
     yum_repository:
      name: Kubernetes
      description: Kubernetes YUM repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: yes

   - name: install kubelet
     yum:
        name: kubelet-1.14.0
        state: present
        update_cache: true

   - name: install kubeadm
     yum:
        name: kubeadm-1.14.0
        state: present

   - name: start kubelet
     service:
       name: kubelet
       enabled: yes
       state: started

- hosts: kubernetes-master
  become: yes
  tasks:
   - name: install kubectl
     yum:
        name: kubectl-1.14.0
        state: present
        allow_downgrade: yes
    
   - name: Pulling images required for setting up a Kubernetes cluster
     shell: kubeadm config images pull    

   - name: Enable the docker.services
     shell: systemctl enable docker.service
   
   - name: initialize the cluster
     shell: sudo kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
     register: output
     args:
       chdir: $HOME
       creates: cluster_initialized.txt

   - name: create .kube directory
     become: yes
     become_user: centos
     file:
       path: $HOME/.kube
       state: directory
       mode: 0755

   - name: copy admin.conf to user's kube config
     copy:
       src: /etc/kubernetes/admin.conf
       dest: /home/centos/.kube/config
       remote_src: yes
       owner: centos

   - name: install Pod network
     become: yes
     become_user: centos
     shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml >> pod_network_setup.txt
     args:
       chdir: $HOME
       creates: pod_network_setup.txt
